---
title: "extra_code_proj103"
author: "Alexandra Treml"
date: "2024-08-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ten_genes <- c("A1BG", "A1CF", "A2M", "A2ML1", "A3GALT2", "A4GALT", "AAAS", "AACS", "AADAC", "AAK1")

df$age <- as.numeric(df$age)

df$age_group <- cut(df$age,
                    breaks = c(21, 30, 50, 70, 88),
                    labels = c("21-30", "31-50", "51-70", "71-88"),
                    right = TRUE)

df_hm <- df %>%
  select(age_group ,gene, expression, mechanical_ventilation)%>%
  filter(gene %in% ten_genes)


ggplot(df_hm, aes(x = gene, y = age_group, fill = expression)) +
  geom_tile() +
  scale_fill_gradient(low = "yellow", high = "red") +
  # Add mechanical ventilation status as an additional tracking bar
  facet_grid(rows = vars(mechanical_ventilation), scales = "free_y") + # This adds mechanical ventilation status as rows
  theme_minimal() +
  labs(title = "Gene Expression Heatmap by Age and Mechanical Ventilation Status", 
       x = "Gene", 
       y = "Age") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1), 
        axis.text.y = element_text(size = 8))

```

