---
title: "Project_part3"
author: "Alexandra Treml"
date: "2024-08-25"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("stargazer")
library(stargazer)
library(dplyr)
library(ggplot2)
```
DATA CLEANING AND PREP
```{r}
#DATA CLEANING AND PREP

# Set the working directory and read in the files
setwd("C:/Users/AlexandraTreml/Desktop/MS/QBS103/Project/QBS103_proj")
genes <- read.csv("genes_GSE157103.csv")
participant <- read.csv("series_matrix_GSE157103.csv")

# Rename the first column in genes to 'gene'
genes <- genes %>%
  rename(gene = X) %>%
  filter(gene == "A2M")

# Pivot the genes dataframe
genes_long <- genes %>%
  tidyr::pivot_longer(cols = -gene, names_to = 'id', values_to = 'expression')

#rename id column in participant, select my categorical covariates and continuous variable (+age for eda)
participant <- participant %>%
  filter(icu_status == ' yes') %>%
  rename(id = participant_id)
  #select(id, age, sex, mechanical_ventilation, lactate.mmol.l.)

#join 2 dataframes
df <- left_join(participant, genes_long, by = "id")

#fill lactate unknowns with NA 
df$lactate.mmol.l.[df$lactate.mmol.l. == " unknown"] <- NA
#fill sex unknowns with NA 
df$sex[df$sex == " unknown"] <- NA
#remove : from age, and fill with NA
df$age[df$age == " :"] <- NA

df <- na.omit(df) #get rid of na
```

Part 1: Latex table of summary stats for all variables. 

```{r}
# Load necessary libraries
library(dplyr)
library(stargazer)
#library(knitr)

# Convert columns to appropriate types
df$fibrinogen <- as.numeric(df$fibrinogen)
df$lactate.mmol.l. <- as.numeric(df$lactate.mmol.l.)
df$expression <- as.numeric(df$expression)
df$sex <- as.factor(df$sex)
df$mechanical_ventilation <- as.factor(df$mechanical_ventilation)
df$gene <- as.factor(df$gene)
df$crp.mg.l. <- as.numeric(df$crp.mg.l.)

# Summary of numeric variables
stargazer(df %>% select(expression, lactate.mmol.l., fibrinogen, crp.mg.l.), 
          type = "text", 
          summary.stat = c("mean", "sd", "n"),
          digits = 2)

sex_counts <- df %>%
  group_by(sex) %>%
  summarize(
    count = n(),
    n_percentage = (n()/nrow(df)) *100)

gene_counts <- df %>%
  group_by(gene) %>%
  summarize(
    count = n(),
    n_percentage = (n()/nrow(df)) *100)

vent_counts <- df %>%
  group_by(mechanical_ventilation) %>%
  summarize(
    count = n(),
    n_percentage = (n()/nrow(df)) *100)

sex_counts <- sex_counts %>%
  mutate(variable = "Sex")

gene_counts <- gene_counts %>%
  mutate(variable = "Gene")

vent_counts <- vent_counts %>%
  mutate(variable = "Mechanical Ventilation")

cat_variables <- bind_rows(sex_counts, gene_counts, vent_counts)

cat_variables <- cat_variables%>%
  select(variable, count, n_percentage)

stargazer(cat_variables, type = "text", summary = FALSE, rownames = FALSE)
```
Part 2: Generate a publication quality histogram, boxplot, and scatterplot
```{r}
df <- na.omit(df)
df <- df %>% 
  select(id, gene, sex, age, mechanical_ventilation, expression, lactate.mmol.l.)
#head(df)

df$sex <- as.factor(df$sex)
levels(df$sex)


ggplot(data = df, aes(x = expression, fill = sex)) + 
  geom_histogram(binwidth = 0.05, position = 'dodge') + 
  labs(x = 'Gene Expression', y = 'Frequency', title = 'A2M Gene Expression Among COVID ICU Patients') +  
  scale_fill_manual(values = c("violetred", "royalblue2"))

```
```{r}
# Convert lactate.mmol.l. to numeric
df$lactate.mmol.l. <- as.numeric(df$lactate.mmol.l.)

# Remove leading and trailing whitespaces from sex column
df$sex <- trimws(df$sex)
df$mechanical_ventilation <- trimws(df$mechanical_ventilation)

# Check unique levels
unique(df$sex)
unique(df$mechanical_ventilation)

# Set factor levels
df$sex <- factor(df$sex, levels = c("male", "female"))
df$mechanical_ventilation <- factor(df$mechanical_ventilation, levels = c("yes", "no"))


# Filter out values greater than 6.5 for the y-axis
df <- df %>% filter(lactate.mmol.l. <= 6.5)

df <- df %>% filter(expression <= 0.5)

# scatterplot vent
ggplot(df, aes(x = expression, y = lactate.mmol.l., color = mechanical_ventilation, shape = mechanical_ventilation)) + 
  geom_point(size = 3) + 
  scale_y_continuous(breaks = seq(0, ceiling(max(df$lactate.mmol.l., na.rm = TRUE)), by = 0.5)) +
  geom_smooth(method = "lm", se = TRUE) + 
  labs(x = 'Gene Expression A2M', y = 'Lactate (mmol/l)', title = ' A2M Gene Expression vs Lactate for COVID ICU Patients') + 
  theme_classic(base_size = 5) +
  scale_color_brewer(palette = 'Dark2') +
  #scale_color_manual(values = c("male" = "royalblue2", "female" = "violetred3")) + 
  scale_shape_manual(values = c(16, 17)) +  
  theme(
    plot.title = element_text(size = 16, face = "bold"), # Center and bold title
    axis.title = element_text(size = 12, face = "bold"), # Bold axis titles
    axis.text = element_text(size = 12), # Increase axis text size
    legend.title = element_text(size = 12), 
    legend.text = element_text(size = 12) 
  )
```
```{r}
df$age <- as.numeric(df$age)

df$age_group <- cut(df$age,
                    breaks = c(21, 30, 50, 70, 88),
                    labels = c("21-30", "31-50", "51-70", "71-88"),
                    right = TRUE)
#head(df)


ggplot(df, aes(x = mechanical_ventilation, y = expression, color = sex)) +
  geom_boxplot() +
  scale_color_manual(values = c("male" = "royalblue1", "female" = "violetred1")) +
  labs(x = 'Mechanical Ventilation', y = 'Gene Expression', title = 'A2M Gene Expression Among Ventilated vs Non-Ventilated COVID ICU Patients') +
  theme_classic()
```
DATA PREP 

```{r}
genes_1 <- read.csv("genes_GSE157103.csv")
participant <- read.csv("series_matrix_GSE157103.csv")


genes_1 <- genes_1 %>%
  rename(gene = X)

# Pivot the genes dataframe
genes_long_1 <- genes_1 %>%
  tidyr::pivot_longer(cols = -gene, names_to = 'id', values_to = 'expression')

#rename id column in participant, select my categorical covariates and continuous variable (+age for eda)
participant <- participant %>%
  filter(icu_status == ' yes') %>%
  rename(id = participant_id)
  #select(id, age, sex, mechanical_ventilation, lactate.mmol.l.)

#join 2 dataframes
df1 <- left_join(participant, genes_long_1, by = "id")

#fill lactate unknowns with NA 
df1$lactate.mmol.l.[df1$lactate.mmol.l. == " unknown"] <- NA
#fill sex unknowns with NA 
df1$sex[df1$sex == " unknown"] <- NA
#remove : from age, and fill with NA
df1$age[df1$age == " :"] <- NA

df1 <- na.omit(df1) #get rid of na

head(df1)
```

Part 3: Generate a Heat Map 
```{r}
library(reshape2)

ten_genes <- c("A1BG", "A1CF", "A2M", "A2ML1", "A3GALT2", "A4GALT", "AAAS", "AACS", "AADAC", "AAK1")

df1$age <- as.numeric(df1$age)

df1$age_group <- cut(df1$age,
                    breaks = c(21, 30, 50, 70, 88),
                    labels = c("21-30", "31-50", "51-70", "71-88"),
                    right = TRUE)

df_hm <- df1 %>%
  select(age_group, gene, expression, mechanical_ventilation, sex)%>%
  filter(gene %in% ten_genes)

#reshape
heatmap_data <- dcast(df_hm, gene ~ age_group, value.var = "expression")
rownames(heatmap_data) <- heatmap_data$gene
heatmap_data <- heatmap_data[ , -1]

#create heatmap with pheatmap
pheatmap(heatmap_data,
         cluster_rows = TRUE,
         cluster_cols = TRUE,
         display_numbers = TRUE,
         number_format = "%.0f",  
         fontsize_number = 6,
         fontsize_row = 10,
         fontsize_col = 10, 
         main = "Gene Expression Heatmap by Age",)
```

Part 4: A plot type we did not discuss in class
```{r}
#percent of people in the ICU on mechanical ventilation

df$mechanical_ventilation <- trimws(df$mechanical_ventilation)

on_vent <- df %>%
  group_by(mechanical_ventilation) %>%
  summarize(count = n())

print(on_vent)
unique(df$mechanical_ventilation)

pie_chart <- ggplot(on_vent, aes(x = "", y = count, fill = mechanical_ventilation)) +
  geom_bar(width = 1, stat = "identity") + 
  coord_polar("y") + 
  labs(title = "Mechanical Ventilation Count Among ICU Patients") +
  theme_void() + 
  scale_fill_manual(values = c("yes" = "darkorange1", "no" = "cornflowerblue")) +
   geom_text(aes(label = count), 
            position = position_stack(vjust = 0.5))

print(pie_chart)
```






